@echo off
echo Adding remote...
git remote remove origin
git remote add origin https://github.com/prof-aadharshr/Replateo.web.git
echo Adding files...
git add .
echo Committing...
git commit -m "fix: Force push via batch script"
echo Pushing...
git branch -M main
git push -u -f origin main
pause
